name: Update Clone Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone Count Badge
        uses: MShawon/github-clone-count-badge@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
